version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: python_auth_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbit:
    image: rabbitmq:3.13-management
    container_name: python_auth_rabbit
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # panel http
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  pgdata:
